image: python:3.6

stages:
- build
- test

before_script:
- pip install -e .
- pip install -r requirements-dev.txt

python36-lint:
  image: python:3.6
  stage: build
  script:
    - flake8 --ignore=E501 fipepy
    - flake8 --ignore=E501 fipeapp

python36:
  image: python:3.6
  stage: test
  script: python -m pytest -s -vv tests
