version: '3.1'

services:
  db:
    image: postgres:10.7
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: example
      POSTGRES_DB: fipepydb
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"


